<?php
/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
return function($container) {
    $instance = new \Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController();
    return $instance;
};
